name: dogfood-msinternal (prod)

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.0.0

      - run: |
          node launch.js > launch.sh
          sh launch.sh

      - uses: actions/upload-artifact@v4
        with:
          path: Dogfood_DevMain_*_x64_O365ProPlusRetail_en-us.zip
